name: maozi_phone_clear
description: 猫子手机清理 - 扫描垃圾文件、勾选清理、统计清理大小
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  crypto: ^3.0.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  path: ^1.9.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
